### ISSUE TITLE
question after my run

### ISSUE THREAD

**Issue by AnabellaHan** [HeliosZhao/M3L#4]
I  ran your project with three GPUs,and i didnot change the code except replacing msmt17v1 with msmt17v2,but it has this question:

File "D:\papercode\M3Lmaster\reid\trainers.py", line 64, in train
    f_out, tri_features = self.model(inputs, MTE='', save_index=save_index)
ValueError: too many values to unpack (expected 2)

Is there something wrong with my dataset? Have you encountered it before? 
Thank you for reading!

**Comment by HeliosZhao** [comment]
Hi, 
From your traceback, it seems that it is not a problem about dataset.
Do you add `--BNNect` when running?

**Comment by AnabellaHan** [comment]
My problem has been solved,Thank you!

**Comment by Cherishhuier** [comment]
Hello, I get the following error when I run your code again, is it because there is a problem with my dataset? Have you encountered such a problem? Thank you very much for visiting.

**Comment by Cherishhuier** [comment]
Hello, I get the following error when I run your code again, is it because there is a problem with my dataset? Have you encountered such a problem? Thank you very much for visiting.
/M3L-master/reid/utils/data/preprocessor.py", line 27, in _get_single_item
    fname, pid, camid, dataset_id = self.dataset[index]
ValueError: not enough values to unpack (expected 4, got 3)

**Comment by Cherishhuier** [comment]
Although the time is a bit long, as a new scientific research, I hope to get your answer, thank you very much.
